Doing more strict matching for IE_COMMENT to avoid conflicts with CDATA tags <unassigned>
Constructs of the following kind with both IE comments and CDATA tags were not
getting parsed correctly, resulting in the below mentioned exception. This patch
fixes this bug by doing more strict matching for the IE_COMMENT_END condition.
<!--[if lt IE 7]>
...
//<![CDATA[ 
...
//]]>
...
<![endif]-->

Exception:
 java.lang.StringIndexOutOfBoundsException: String index out of range: -2
       at java.lang.String.substring(String.java:1949)
       at
com.google.caja.parser.html.Html5ElementStack.processComment(Html5ElementStack.java:459)
       at com.google.caja.parser.html.DomParser.parseDom(DomParser.java:589)
       at
com.google.caja.parser.html.DomParser.parseDocument(DomParser.java:206)

http://codereview.appspot.com/4641089/

R=pulkitgoyal2000@gmail.com, jasvir@gmail.com, mikesamuel@gmail.com


git-svn-id: https://google-caja.googlecode.com/svn/trunk@4535 360991c0-9f3b-0410-ba87-8b362a00edf4